name: WebdriverIO E2E Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'

      - name: Install dependencies
        run: npm install

      - name: Download and install ChromeDriver
        run: |
          CHROMEDRIVER_VERSION="93.0.4577.15"
          wget -q -O /tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
          unzip /tmp/chromedriver.zip -d /tmp
          chmod +x /tmp/chromedriver
          mv /tmp/chromedriver /usr/local/bin/chromedriver

      #- name: Set display configuration (if running in a headless environment)
      #  run: export DISPLAY=:99
        
      - name: Set environment variables
        env:
          USERNAME: ${{ secrets.USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}
        run: echo "USERNAME=$USERNAME\nPASSWORD=$PASSWORD" >> .env

    

      - name: Run tests
        run: npm test
